### ISSUE TITLE
Playwaze items don't have unique IDs

### ISSUE THREAD

**Issue by tomoakley** [Playwaze/opendata#1]
Hi,

Some IDs in your endpoint are used multiple times for different items - while these items are the same (i.e a weekly Parkour session), they should each have unique IDs to identify them. Either that or they should be courses instead. For example:

    {
      "data": {
        "GroupPlay": {
          "activity_name": "Thursday Men's Tennis"
          // etc
        },
        "end_date": "2017-06-29T21:30:00Z",
        "start_date": "2017-06-29T19:00:00Z",
        // etc
      },
      "id": "kf43m8rw8w5id",
      "kind": "session",
      "modified": 1498636001,
      "state": "updated"
    }

and

    {
      "data": {
        "GroupPlay": {
          "activity_name": "Thursday Men's Tennis"
          // etc
        },
        "end_date": "2017-06-07T21:30:00Z",
        "start_date": "2017-06-07T19:00:00Z",
        // etc
      },
      "id": "kf43m8rw8w5id",
      "kind": "session",
      "modified": 1498636001,
      "state": "updated"
    },

should have different IDs.

**Comment by rujenner** [comment]
Hi Tom,

Agreed. It's currently showing the ID for the Sessions container (Group Play). I have raised a request to change this to a Session ID which will be unique. Thanks for pointing out. Will post back when that's done.

**Comment by rujenner** [comment]
This is resolved now.
