### ISSUE TITLE
OpenActive compliance

### ISSUE THREAD

**Issue by civsiv** [Playwaze/opendata#4]
Hi, 

We at imin have been looking at different OpenActive endpoints to improve our platform, and have noticed that there are a few discrepancies between your session data and the OpenActive specification. Would it be possible for you to look at them?
An example of the OpenActive specification can be found here: https://www.openactive.io/realtime-paged-data-exchange/#example

Thanks,
Civ

**Comment by domfennell** [comment]
Hi Playwaze,

Hope all's well.

Just following up on @civsiv's question from a couple of weeks ago, just wondering if there is an issue with your OA feed, as it isn't returning any results for me? Simply returning `"next": null`.

Best,

Dom

**Comment by rujenner** [comment]
Hi Dom,

Ah yes - we did a big data migration last week and this may have caused this. I'll get our devs on to it.

Regards,
Rupert

**Comment by domfennell** [comment]
Much appreciated, @rujenner!

Hopefully your devs can also check to see if the fix addresses @civsiv's initial comment RE session data and the OpenActive specification discrepancies?

Have a good weekend.
