### ISSUE TITLE
Events feed feedback

### ISSUE THREAD

**Issue by domfennell** [Playwaze/opendata#5]
Hi,

We've taken a look at your events feed and have some feedback that might help improve the data in there for those who consume it.

### Location information

It appears that a number of Events have minimal location information, including just a postcode and a lat/lng.  For example, Event with id `56618-B` has the following location object:

```
"location": {
"@type": "Place",
"name": "CH2 2AU",
"address": "CH2 2AU",
"geo": {
"@type": "GeoCoordinates",
"latitude": 53.1961789,
"longitude": -2.8912583
}
},
```

Our assumption, based on the lat/lng above, it that this Event is taking place at Brio's Northgate Arena Chester. However, with a postcode included as the `name` rather than a legitimate name, we are not able to include this information in our platform.

### Confusing `activity` objects

Some Events have an `activity` object that contains information inconsistent with the Events' titles, e.g. `gqn99eqjbi3`: a badminton volunteering Event by name, but american football by activity type.

### Issue with some descriptions

Some descriptions appear like, e.g. `"description": "Tuesdays\r\n7:30 - 9:30pm"` for Event with id `58407-C`.

### Providing more information for the end user

- There does not appear to be age-related data included in the feed.
- There do not appear to be any activity images or provider logos included.
- We could only find Events with `"price": 0` in the `offers` array. Should we be expecting any other prices to appear in the feed?
- We know there is `"beta:attendeeCount": 0` (should we expect this to ever be more than 0?), but is there a notion of availability/remaining available spaces?

Do please let us know if you need any further information or when you might be able to address some of these issues. And apologies if any of the above feedback is based on an oversight on our part.

Very best,

Dom

**Comment by domfennell** [comment]
### Location information

Some Events still have limited location information, including just a name and a lat/lng.  For example, Event with id `fxswox3eppu` has the following location object:

```
"location": {
"@type": "Place",
"name": "Founders Hall",
"address": "Founders Hall",
"geo": {
"@type": "GeoCoordinates",
"latitude": 36.0661331,
"longitude": -94.1748359
}
},
```

- Is this because the provider has yet to complete this information? Could you make the requisite fields mandatory in the Playwaze session uploader portal to ensure that a comprehensive address is listed?
- How is the lat/lng being generated from just "Founders Hall? These coordinates currently point to Arkansas, USA, which might be correct for "Bath Active Sessions".

We're also seeing that a number of Events in our platform still only have a postcode and a lat/lng, e.g. `59707-C` has the postcode `HR2 7NG`, which presumably pertains to The Hereford Academy (?). This session will not be visible in our APIs because of insufficient location information.

### Issue with some descriptions

Thanks for addressing the issue whereby some special characters appearing in descriptions. We're still noticing that some descriptions are duplicating the session schedule, e.g. `"5pm-7pm @ Brunel Sportspark 3G"` = when and where. Could the community leader be encouraged (using examples in the text fields?) to add more comprehensive information, e.g. bibs will be provided, bring a water bottle, etc.?

### Providing more information for the end user

- There does not appear to be age-related data included in the feed.
- ~There do not appear to be any activity images or provider logos included.~ **Thanks for adding images.**
- ~We could only find Events with `"price": 0` in the `offers` array. Should we be expecting any other prices to appear in the feed?~ **Thanks for checking this.**
- We know there is `"beta:attendeeCount": 0` (should we expect this to ever be more than 0?), but is there a notion of availability/remaining available spaces? **We're still only seeing `"beta:attendeeCount": 0`... Does this tell us that every session in the feed currently has `0` attendees? Also, same question from last comment: is there a notion of availability/remaining available spaces?**

**Comment by JoshuaLevett** [comment]
- The issue with the attendeeCount has been sorted, and will come across correctly, along with other attendance information (such as maximumAttendeeCapacity)
- Age and gender restrictions are now enter-able in Playwaze, though still optional, we would expect to see this begin to be included now.
- Special characters are being removed from descriptions where they weren't before (e.g. \r \n).
- Enhancements were made to help prevent confusing activities, like you mentioned.
- We have made changes so that Location should now be properly structured and useful to a consumer of the data (without the context usually available in our system).

**Comment by domfennell** [comment]
Hi @JoshuaLevett, thanks for the update.

One other thing I noticed with regards to the location information provided is that the `location` object within the `superevent` has a `name` that exactly mirrors the `address`, for example:

```
"name": "Woking Park, Woking, UK",
"address": "Woking Park, Woking, UK"
```

The impact of this will be that the full address will appear twice on the front end. Would expect the `name` to be `"Woking Park"` and the address to be `"Woking Park, Woking, UK"`.

**Comment by JoshuaLevett** [comment]
Good spot, I had missed setting up the location properly in the feed for those super events.
Whilst on the topic, though normally the location for the super will be the same as the event, it is possible for an individual event to take place in a different location.

**Comment by JoshuaLevett** [comment]
I believe that everything mentioned has been actioned.
As a recap to the current state of the feed.

Feed problems that have been fixed:

- attendeeCount has been sorted, along with other attendance information (such as maximumAttendeeCapacity)
- Special characters are being removed from descriptions where they weren't before (e.g. \r \n).

Additions that will require user input:

- Age and gender restrictions are now enter-able in Playwaze, though still optional, we would expect to see this begin to be included now.
- Enhancements were made to help prevent confusing activities, like you mentioned, and they should now match up properly to open active activities (though there may still be old data that doesn't).
- We have made changes so that Location should now be properly structured and useful.

**Comment by charlieclarke5** [comment]
@domfennell based on the above please can you do your final QA, with a hope/expectation that you will be able to begin publishing Playwaze hosted data where quality is high. We will actively begin looking to improve data quality of legacy data with our users. 

@JoshuaLevett @rujenner FYI

**Comment by domfennell** [comment]
One other thing I noticed, @JoshuaLevett, is that some sessions have a location that is not a tangible building, but instead a name of a park, e.g. [Cofton Park](https://www.google.com/maps/place/Cofton+Park/@52.3858551,-1.9897484,15z/data=!4m2!3m1!1s0x0:0x130680f694bf67a0?sa=X&ved=2ahUKEwitoeCdk-DnAhWXQkEAHQEZApIQ_BIwE3oECBIQCA) in session with id `56924-A` located in the RPDE feed [here](https://playwazeuat.apphb.com//WebServices/PlayWazeService.svc/OpenData/Events?afterTimestamp=1582016319839&afterId=9fakr5c2tauque):

```
"location": {
"@type": "Place",
"identifier": "31946-A",
"name": "cofton park",
"address": "Cofton Park, Northfield, Birmingham, UK",
"geo": {
"@type": "GeoCoordinates",
"name": "cofton park",
"latitude": 52.3858551,
"longitude": -1.9897484,
"address": "Cofton Park, Northfield, Birmingham, UK"
}
},
```

As far as I can see, this session has no concept of meeting point, which could be confusing for the end user. The `oa:meetingPoint` property in [the OpenActive Spec](https://www.openactive.io/modelling-opportunity-data/#describing-events-code-schema-event-code-) is optional, but "_Some larger locations may have several possible meeting points, so this property provides additional more specific directions_", e.g. a park.

Just a thought.

**Comment by JoshuaLevett** [comment]
Normally, this information would be included in the location description (as it is in our structure).
However it looks like we may have been a bit slack in filling that out for the test data.

As an example

```
"location": {
                    "@type": "Place",
                    "identifier": "31943-A",
                    "name": "Woking Park",
                    "description": "This is part of a development test, all attendees should meet at the centre.",
                    "address": "Woking Park, Woking, UK",
                    "geo": {
                        "@type": "GeoCoordinates",
                        "name": "Woking Park",
                        "latitude": 51.3119799,
                        "longitude": -0.5557936,
                        "address": "Woking Park, Woking, UK"
                    }
                }
```
