### ISSUE TITLE
Feed is broken when trying to visit 'next' pages

### ISSUE THREAD

**Issue by jonferguson** [Playwaze/opendata#8]
Hi there,

We noticed that the data we're importing from your feed hasn't updated in a while. On further inspection, we found the next url in the feeds is broken and redirecting to a login screen:

https://playwaze.com/OpenData/SessionSeries?afterTimestamp=1615856466662&afterId=5p5az3d3g93co

I don't know if this is happening on other feeds as well.

Cheers,
Jon

**Comment by jonferguson** [comment]
Hi there, any update on this?

**Comment by charlieclarke5** [comment]
Hi @jonferguson 

Sorry I'm not sure we have been aware of this. Let me get it investigated for you. 

@JoshuaLevett for your awareness. I will add to our issue board.

Charlie

**Comment by charlieclarke5** [comment]
@JoshuaLevett This is raised as 1488322979 on our internal issue board.

**Comment by charlieclarke5** [comment]
Hi @jonferguson

Hope you are well.

Just to close this off, this was resolved several weeks back.

Take care,

Charlie
